### ISSUE TITLE
ElseIf statements not compiling correctly.

### ISSUE THREAD

**Issue by Yomanz** [FredyH/scalup#2]
Unminified Code:
![image](https://user-images.githubusercontent.com/5119107/81020867-b8b40980-8e61-11ea-8785-fa35f2dc40f2.png)

Minified Code:
![image](https://user-images.githubusercontent.com/5119107/81020873-bce02700-8e61-11ea-9920-969d37e71627.png)

Issue:
The condition and body aren't retrospective of the actual code.

Fix:
The condition and body need to reflect the ElseIf statement.

**Comment by KGoodale13** [comment]
Nice find! Thank you!
